### ISSUE TITLE
cppcheck errors/warnings not cleared when source file updated

### ISSUE THREAD

**Issue by alegacy** [johnthagen/clion-cppcheck#14]
### Environment

* Operating System (e.g. Ubuntu 16.04 x64): 
 CentOS Linux release 7.3.1611 (Core)

* IDE Version (e.g. CLion 2016.3.2):
CLion 2017.3.3 

* Cppcheck executable version (`cppcheck --version`): 
Cppcheck 1.80

* Cppcheck plugin version:
1.0.10

* Exact strings used in cppcheck plugin options:
  * **cppcheck path**:
/usr/bin/cppcheck

  * **cppcheck options**: 
--enable=warning,performance,portability,style --inline-suppr --suppress=unusedStructMember --suppress=variableScope --suppress=uninitvar --language=c

### Expected behaviour
If a warning/error that was reported by cppcheck is fixed then I would expect that the current file would be updated and the warning/error would be removed (i.e., the underline would be removed)

### Actual behaviour
The error remains on the original line number.  If the error was fixed without adding/removing any lines then the error remains on that same line.  If lines are added or removed the error still points to the old line number even though that line has nothing to do with the error being reported.

I find that I have to edit the cppcheck plugin configuration and save/apply them in order to get the file to be re-analyzed again.  Just editing the file is not enough.

### Steps to reproduce the behaviour
1. edit a file and introduce an error that cppcheck will find (in my case that was a "redundantAssignment" style error).  
2. wait for analysis to complete and observe that a warning is now present
3. fix the error
4. wait for analysis to complete and observer that the warning is still present even though it was fixed.

**Comment by johnthagen** [comment]
Hmm, the plugin gets fired by CLion by an event, so we are somewhat at the mercy of CLion to determine when the plugin runs.

One of the main challenges with the way this plugin works is that it shells out to `cppcheck` and calls it on the source file on disk. Because IntelliJ-based products use a virtual filesystem, these can be out of sync with what you see in the IDE, which manifests itself in the slow to update, often out of sync warnings appearing in the IDE.

A better solution would be to take the virtual file from CLion and pipe that into Cppcheck, but unfortunately I don't have the time to explore something like that.

**Comment by fastasturtle** [comment]
To clarify further: currently the plugin just runs `cppcheck <options> <path to file>`, so it has no way to see the unsaved changes that are currently in the editor (and, obviously, saving a file after each typing possible but probably unwanted).

To make things worse, inspection passes in CLion are generally not re-run on save, as the text in the editor is not modified, so it would be redundant. So, worst-case scenario, there is no way to get up-to-date annotations:

1. you type in the editor
2. cppcheck runs but doesn't see new changes, producing an obsolete diagnostics
3. file is saved, but the text in the editor is not changed and highlighting is not re-run
4. goto 1

The proper way to solve it would be to save the unsaved text to a temporary file and run cppcheck against it. There is some more work required (i.e. you'll have to add the original file's directory to header search path), but otherwise, it should work (CLion's clang-tidy integration works more or less this way).

I'll try to create a PR if I'll have time.

**Comment by johnthagen** [comment]
@alegacy Could you confirm if [1.2.0](https://plugins.jetbrains.com/plugin/8143-cppcheck/update/44986) fixes your issues?

**Comment by alegacy** [comment]
Yes, works much better.  Thank you!

Tested with version 1.2.0 on CLion 2018.1.1 (Build #CL-181.4445.84)
