### ISSUE TITLE
Improve error feedback

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/clion-cppcheck#18]
Currently if the user mis-configures something, only a small text is shown in the bottom status bar. It would be good if we could provide more obvious error messages to the user.

**Comment by firewave** [comment]
Can we consider this fixed by 2f8a753533f990f2543ffcde89fa1212e1322ac3? Or is there more to expect?

I am currently trying to implement an action which will provide the raw output for the current file similar to the `Show Clang-Tidy Info` action CLion offers. I am also considering doing this for `--debug` output so it is easier for people to figure out what is going on as well as reporting bugs upstream to Cppcheck. Won't hit a PR until I have finished the XML and several other fixes though.

Sorry I missed this ticket in my commit.

**Comment by johnthagen** [comment]
Yes, I think we can consider this fixed. Thanks.
