### ISSUE TITLE
Plugin is available for *all* IntelliJ-based IDEs

### ISSUE THREAD

**Issue by firewave** [johnthagen/clion-cppcheck#49]
See https://plugins.jetbrains.com/plugin/8143-cppcheck/versions

![image](https://user-images.githubusercontent.com/242857/97893565-bad42380-1d31-11eb-9474-78e596af5628.png)

As this plugin only works with C/C++ source code it should probably be limited to IDEs which are actually target this kind of code - which is only CLion as far as I can see.

**Comment by johnthagen** [comment]
This is actually intentional. If you want to open up some .cpp files in PyCharm or Intellij and use Cppcheck, I didn't want to artificially limit users.

At least AppCode is one other dedicated option: https://www.jetbrains.com/cpp/

Since we aren't using any CLion-specific API's, I'd like to keep this plugin as broadly compatible if possible. I don't think this will trip up users.
